// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShiftLogger.Models;

#nullable disable

namespace ShiftLogger.Migrations
{
    [DbContext(typeof(ShiftLoggerDbContext))]
    [Migration("20251027015323_DataBaseModifcationRelationShipCreation")]
    partial class DataBaseModifcationRelationShipCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShiftLogger.Models.ShiftLoggerEntity.ShifLoggerEntity+EmployeeList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EmployeeList");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 9, 16, 5, 49, 50, 880, DateTimeKind.Unspecified),
                            Name = "Raj"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 9, 17, 8, 23, 10, 320, DateTimeKind.Unspecified),
                            Name = "Kumar"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 9, 18, 10, 11, 22, 500, DateTimeKind.Unspecified),
                            Name = "Priya"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 9, 19, 12, 45, 35, 250, DateTimeKind.Unspecified),
                            Name = "Suresh"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 9, 20, 14, 5, 45, 880, DateTimeKind.Unspecified),
                            Name = "Anita"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2025, 9, 21, 16, 15, 55, 123, DateTimeKind.Unspecified),
                            Name = "Manoj"
                        },
                        new
                        {
                            Id = 7,
                            CreatedDate = new DateTime(2025, 9, 22, 18, 25, 35, 600, DateTimeKind.Unspecified),
                            Name = "Divya"
                        },
                        new
                        {
                            Id = 8,
                            CreatedDate = new DateTime(2025, 9, 23, 19, 30, 15, 770, DateTimeKind.Unspecified),
                            Name = "Vijay"
                        },
                        new
                        {
                            Id = 9,
                            CreatedDate = new DateTime(2025, 9, 24, 20, 45, 55, 980, DateTimeKind.Unspecified),
                            Name = "Sneha"
                        },
                        new
                        {
                            Id = 10,
                            CreatedDate = new DateTime(2025, 9, 25, 21, 55, 5, 440, DateTimeKind.Unspecified),
                            Name = "Arun"
                        },
                        new
                        {
                            Id = 11,
                            CreatedDate = new DateTime(2025, 9, 26, 22, 10, 30, 210, DateTimeKind.Unspecified),
                            Name = "Lakshmi"
                        });
                });

            modelBuilder.Entity("ShiftLogger.Models.ShiftLoggerEntity.ShifLoggerEntity+ShiftDetails", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ShiftEnd")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ShiftStart")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("ShiftStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<decimal>("TotalWorkingHours")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("ShiftDetails");
                });

            modelBuilder.Entity("ShiftLogger.Models.ShiftLoggerEntity.ShifLoggerEntity+ShiftDetails", b =>
                {
                    b.HasOne("ShiftLogger.Models.ShiftLoggerEntity.ShifLoggerEntity+EmployeeList", "Employee")
                        .WithMany("Shifts")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("ShiftLogger.Models.ShiftLoggerEntity.ShifLoggerEntity+EmployeeList", b =>
                {
                    b.Navigation("Shifts");
                });
#pragma warning restore 612, 618
        }
    }
}
